export const TodasLasImagenes = [
    {id: 1,
     imagen: "/src/imagenes/busto1.jpg",
    
    },
    {id: 2,
        imagen: "/src/imagenes/busto2.jpg",
        },
    {id: 3,
        imagen: "/src/imagenes/canasta1.jpg", 
        },   
    {id: 4,
      imagen: "/src/imagenes/carbonera.jpg", 
    },
    {id: 5,
        imagen: "/src/imagenes/custodio1.jpg", 
      },
    {id: 6,
        imagen: "/src/imagenes/custodio1a.jpg", 
    },
    {id: 7,
        imagen: "/src/imagenes/custodio2.jpg", 
      },
    {id: 8,
        imagen: "/src/imagenes/custodio2b.jpg", 
      },
    {id: 9,
        imagen: "/src/imagenes/figurillas1.jpg", 
      },
    {id: 10,
        imagen: "/src/imagenes/figurillas2.jpg", 
      },
      {id: 11,
        imagen: "/src/imagenes/figurillas3.jpg", 
      },
      {id: 12,
        imagen: "/src/imagenes/figurillas4.jpg", 
      },
      {id: 13,
        imagen: "/src/imagenes/figurillas5.jpg", 
      },
      {id: 14,
        imagen: "/src/imagenes/figurillas6.jpg", 
      },
      {id: 15,
        imagen: "/src/imagenes/jarra1.jpg", 
      },
      {id: 16,
        imagen: "/src/imagenes/jarra2.jpg", 
      },
      {id: 17,
        imagen: "/src/imagenes/Mascara_01_baja 24x17x10.jpg", 
      },
      {id: 18,
        imagen: "/src/imagenes/Mascara_02_baja23x15x6.jpg", 
      },
      {id: 19,
        imagen: "/src/imagenes/Mascara_03_baja24x18x8.jpg", 
      },
      {id: 20,
        imagen: "/src/imagenes/Mascara_04_baja25x20x10.jpg", 
      },
      {id: 21,
        imagen: "/src/imagenes/Mascara_05_baja23x17x8.jpg", 
      },
      {id: 22,
        imagen: "/src/imagenes/Mascara_06_baja24x18x6,5.jpg", 
      },
      {id: 23,
        imagen: "/src/imagenes/Mascara_07_baja18x22x11.jpg", 
      },
      {id: 24,
        imagen: "/src/imagenes/Mascara_08_baja25x17x7.jpg", 
      },
      {id: 25,
        imagen: "/src/imagenes/Mascara_09_baja28x19x9.jpg", 
      },
      {id: 26,
        imagen: "/src/imagenes/Mascara_10_baja21x17x12.jpg", 
      },
      {id: 27,
        imagen: "/src/imagenes/Mascara_11_baja25x18x10.jpg", 
      },
      {id: 28,
        imagen: "/src/imagenes/Mascara_12_baja27x19x10.jpg", 
      },
      {id: 29,
        imagen: "/src/imagenes/MUESTRA1.jpg", 
      },
      {id: 30,
        imagen: "/src/imagenes/MUESTRA2.jpg", 
      },
      {id: 31,
        imagen: "/src/imagenes/MUESTRA3.jpg", 
      },
      {id: 32,
        imagen: "/src/imagenes/MUESTRA4.jpg", 
      },
      {id: 33,
        imagen: "/src/imagenes/negra1.jpg", 
      },
      {id: 34,
        imagen: "/src/imagenes/negra2.jpg", 
      },
      {id: 35,
        imagen: "/src/imagenes/pieza1.jpg", 
      },
      {id: 36,
        imagen: "/src/imagenes/pieza1b.jpg", 
      },
      {id: 37,
        imagen: "/src/imagenes/pueza1a.jpg", 
      },
]
